### ISSUE TITLE
TODOメモ

### ISSUE THREAD

**Issue by shuntaka9576** [shuntaka9576/CouponsAPI#1]
本issueはメモとして利用する
解決の目処がたったら、issueを新たに起票し対応する
#### 優先度 高
* [ ] ドキュメント作成
* [x] コメント整理
* [x] 不要コードの削除
* [x] swaggerデモ対応
* [ ] 画像作成
* [x] POST対応 4/13 9b46a2500efd956f61df635da958a8d4aebee42d #4 
* [x] 不正な日付を入れた時のエラーハンドリング(現在はinternal server error)
* [x] dynamo問い合わせ時のエラーハンドリング
  * [x] getId 4/14 05cb1931cc6ce95528c66e1448f2a2e852946a4d
    * [x] 実装
    * [x] テスト追加
  * [x] getList 4/14 1091537d04abfe344faa079ba419810b831cee26
    * [x] 実装
    * [x] テスト追加
#### 優先度 低
* [ ] GET /coupons/{id}?date=20190405 実装見送り
* [ ] POST /coupons/{id}?date=20190405 実装見送り
* [ ] E2Eテスト記述
* [ ] カバレッジ向上
* [ ] GETとPOSTでテーストケースの共通化
* [ ] initdynamoのテストの事前処理で、s3のファイルが在る/削除されていることを確認する処理がない
* [ ] `CloudWatch`のロググループをdeploy前に削除するスクリプトの作成、組み込み
* [x] レスポンスJSONがユニコードエスケープされている 6375e317aa39a4697fd83814fefe33c77d237ac6
* [ ]  S3上の古い世代のLambdaソースを削除するスクリプトの作成、組み込み
* [ ]  CloudFormationを削除している間ポーリングし、完了したらデプロイするスクリプトの作成、組み込み
* [x] SwaggerUIでdemo出来る様にする
* [x] couponAPIに期間の概念を加えて、準じたAPIを実装する
### 調査系
* cerberusはNoneであることをバリデーションすることは出来なさそう..
  * 出来れば`/coupons`問い合わせは、`events["pathPrameter"]` が`None`であることをバリデーションしたい
### 課題
* [x]  APIGateWayのドメインがデプロイ毎に変わる。対策しないとサービスには使えない
  * CFnを削除しないくてもコードの更新は可能なので、解決
* [ ] デプロイ時と開発時で、Pythonのパッケージ構成(テストライブラリが必要でboto3がいらない等)が異なるため、デプロイした後開発用にパッケージを落とし直す必要がある
* [ ] ユニットテストが中で関数内で使われているライブラリの挙動も含まれた上での結果比較になっている
* [x] swagger.yamlをSAMから読んでいるが、活用出来ていない
* [ ] 完全に分離できる関数のコードも含めてデプロイをしている(コードベースが大きくなると問題あり?)
* [ ] サブテスト対応していないため、テストケースを配列で持たせているがどこで落ちたか分かりにくい
  * [ ] unittestならサブテストがありそう?
* [ ] 標準出力に出している内容もテストがしたい
* [ ] APIGatewayが返すエラーメッセージのカスタマイズ(テストケースを余計に書きすぎている)

**Comment by shuntaka9576** [comment]
## couponAPIに期間の概念を加えて、準じたAPIを実装する
### TODO
[ ] dynamo対応
[ ] /coupons対応
[ ] テスト対応
